<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>zz</string>
   </array>
  <key>name</key>
  <string>zamuza</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.zamuza</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([_a-zA-Z][_0-9a-zA-Z]*&apos;*)</string>
          <key>name</key>
          <string>entity.name.class.zamuza</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#name</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#punct</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
       </array>
    </dict>
    <key>comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.zamuza</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.zamuza</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.zamuza</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>name</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>((#|@)[_a-zA-Z])</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.zamuza</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#name__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?:([^0-9a-zA-Z\x{0027}]|$))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.zamuza</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>name__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([_0-9a-zA-Z]*&apos;*)</string>
          <key>name</key>
          <string>variable.zamuza</string>
        </dict>
       </array>
    </dict>
    <key>punct</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(&gt;&gt;|&lt;&lt;|-&gt;|&lt;-)</string>
          <key>name</key>
          <string>keyword punctuation.zamuza</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(=&gt;|\|&gt;|&lt;\|)</string>
          <key>name</key>
          <string>punctuation.zamuza</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
